extends Node



var path := "user://saveData.json"
var path_visited = "user://visited.json"
	
var save_data := {
	"username": "",
	"scene": "0",
	"settings": {
		"crt": true,
		"fullscreen": false,
		"gameVolume": 100,
		"musicVolume": 100,
		"skip_animation": false
	}
}

var username = ""

var storia_classed = [
	Storia.new("0", "intro", "L'anno è il 1993, ti trovi in una grande città piena di palazzi altissimi appena costruiti.\n\nIl tuo appartamento è al 14° piano di un edificio fatiscente, la \"Casa del Codice\", un ex condominio trasformato in cubicoli per programmatori squattrinati.\n\nL'aria sa di caffè bruciato e polvere di circuiti.\n\nSulla scrivania, un 486 DX2 ronza come un alveare arrabbiato, circondato da torri di floppy disk etichettati \"BACKUP_12\" e \"PROGETTO_ALFA\".\n\nUn poster stinto di \"WarGames\" pende storto sopra un divano-letto ricoperto da pile di manuali: \"TCP/IP Illustrated\", \"The C Programming Language\", \"Hacker's Delight\""),
	Storia.new("0.1", "rovista tra la posta", "Ti avvicini alla porta imbarcata del tuo appartamento e, spostando alcune riviste informatiche, trovi una piccola pila di buste. Tra queste c'è un pacco anonimo di medie dimensioni, avvolto in carta marrone e sigillato con dello scotch da imballaggio. Lo metti momentaneamente sulla scrivania. Sotto il pacco, una busta gialla cattura la tua attenzione. L'apri e il tuo stomaco si contrae: è la bolletta della luce scaduta da tre giorni. $87.42 che non hai ancora messo da parte. Il tuo conto in banca è pericolosamente vicino allo zero dopo aver pagato l'affitto e comprato quel nuovo modem a 14.4k che ti serviva per i tuoi \"progetti personali\""),
	Storia.new("0.2", "affacciati alla finestra", "Ti avvicini alla finestra appannata e pulisci un cerchio di condensa con la manica. Fuori, la pioggia cade incessante, creando riflessi caleidoscopici nelle pozzanghere che specchiano le insegne al neon dei locali sulla strada principale. \"LUCKY DRAGON TAKE-AWAY\" lampeggia in rosso e verde, mentre più in basso l'insegna blu del \"CYBER CAFÉ\" promette \"ACCESSO INTERNET $5/ORA\".\nI marciapiedi sono quasi deserti a quest'ora. Un paio di cassonetti ribaltati hanno vomitato il loro contenuto sull'asfalto bagnato. Un gatto randagio fruga tra i rifiuti.\nL'unica figura umana visibile è un ragazzo con un impermeabile giallo, completamente inzuppato nonostante la protezione. Sta infilando riviste in buca lettere e portoni. Riconosci la copertina di \"PC World\" con il titolo a caratteri cubitali: \"RIVOLUZIONE PENTACORE: IL NUOVO PROCESSORE INTELLIX CAMBIA TUTTO\". Ti chiedi quando potrai permettertene uno."),
	Storia.new("0.3", "guarda il calendario", "Il calendario appeso al muro porta l'intestazione \"MicroTech Solutions - Costruiamo il Futuro Digitale, un Byte alla Volta\". Il logo aziendale - un microchip stilizzato con un fulmine.\n\nLe date cerchiate:\n- 7/10: “+28 - anno in più ma stessi problemi”\n- 12/10: \"Consegna modulo fiscale X-22 - BOSS URLA!\"\n- 18/10: \"Demo progetto ‘Aurora’ - MIKE PRENDE IL MERITO.\"\n- 25/10: \"Stipendio (se arriva)\n- 27/10 (domani): \"Deadline Progetto Nebula - CONSEGNA FINALE\".\n\nHai passato le ultime tre settimane a lavorare 16 ore al giorno su quel maledetto sistema.\n\nSotto Ottobre una citazione del CEO:\n\"Il codice perfetto non ha bisogno di firma.\"\nTu hai aggiunto a penna: \"…perché qualcun altro la ruba.\""),
	Storia.new("1", "siediti alla scrivania", "Ti siedi alla scrivania, sorseggiando la tua cioccolata calda da una tazza con la scritta “ERROR 418: I’m a teapot”. Il cuoio sintetico della sedia emette un gemito familiare.\nIl monitor illumina il tuo volto con la sua luce spettrale. è tardi, ma il sonno è l'ultimo dei tuoi pensieri."),
	Storia.new("1.1", "apri il pacco", "Incuriosito, prendi il pacco. Non c'è mittente, solo il tuo indirizzo scritto con una calligrafia precisa: \"Alex Chen, Via delle Industrie 128, Int. 14B\". Il pacco è leggero e ha la forma inconfondibile di un libro.\nRompi il sigillo di scotch e scarti la carta marrone. Dentro c'è un volume rilegato in similpelle nera: \"Network Security: The Coming Frontier\". è un testo recente, pubblicato appena sei mesi fa, che hai visto in libreria a $75 - troppo per il tuo budget attuale.\nSfogliando le prime pagine, un post-it giallo cade sul pavimento. Lo raccogli: c'è un numero di telefono scritto a mano e due lettere in calce: \"DK\"."),
	Storia.new("1.1.1", "chiama il numero trovato", "Con una strana sensazione di aspettativa, componi il numero sul tuo telefono. Tre squilli, poi una voce maschile, profonda e modulata risponde:\n\"Finalmente hai chiamato, Alex.\"\n\"Chi parla? Come fa a conoscere il mio nome?\" chiedi, con un misto di curiosità e sospetto.\nUna breve risata dall'altro capo.\n\"Chiamami DK. Diciamo che ho notato il tuo talento... nonostante i tuoi superiori a MicroTech sembrino ciechi.\"\n\"Come sa dove lavoro?\" Il tuo cuore accelera leggermente.\n\"So molte cose, Alex. E so che stai sprecando il tuo potenziale. Il futuro non è nella programmazione aziendale... è nelle reti. Nei sistemi. Nel controllo dell'informazione.\"\n\"Cosa vuole da me?\" chiedi, affascinato e cauto allo stesso tempo.\n\"Non è questione di cosa voglio io, ma di cosa vuoi tu. Libertà? Riconoscimento? Vendetta? O semplicemente usare il tuo cervello per qualcosa che valga la pena?\" Una pausa. \"Una volta che lo avrai scoperto controlla la tua mail. Non deludermi, mi raccomando!\"\nLa linea si interrompe."),
	Storia.new("1.1.2", "ignori il numero trovato", "Ti senti troppo impaurito per chiamare ma continui a riflettere guardando il monitor del tuo pc"),
	Storia.new("1.2", "apri il BBS (Bulletin Board System)", "Avvii il tuo software di comunicazione e il modem inizia la sua familiare sinfonia di toni e fruscii. Dopo alcuni secondi, sei connesso al \"Digital Underground BBS\", uno dei tuoi preferiti per la sua comunità tecnica e le discussioni senza censura.\nDopo aver inserito username e password, ti appare il menu principale:\n┌───────────────── DIGITAL UNDERGROUND BBS ─────────────────┐\n│                                                           │\n│ [1] General Chat                                          │\n│ [2] Programming & Hacking                                 │\n│ [3] Games & Demos                                         │\n│ [4] File Downloads (limited access)                       │\n│ [5] System Messages                                       │\n│                                                           │\n│ Users Online: 17    Last Updated: 23:42:15                │\n└───────────────────────────────────────────────────────────┘"),
	Storia.new("1.2.1", "general chat", "Entri nell'area di chat generale. Una conversazione è in corso:\n\n<BYTEBANDIT> quindi ho overclockato la cpu e boom, kernel panic\n<BLASING> classico. hai controllato il dissipatore?\n<DATANINJA> ragazzi, qualcuno ha sentito del raid dell'fbi a pittsburgh?\n<VIRUSVANDAL> ehi gente, manteniamo la chat pulita. sai che ho le mie regole\n<DATANINJA> è pubblico vandal, era sul nytimes\n<BYTEBANDIT> ehi @CODEMASTER, da quanto tempo! novità?\n\nSembra la solita chiacchierata. Nulla di particolarmente interessante stasera."),
	Storia.new("1.2.2", "programming & hacking", "L'area di programmazione è piena dei soliti thread:\n\"Ottimizzare cicli in C++\"\n\"Problemi con interrupt 21h\"\n\"Tutorial: Social Engineering basics\"\n\"HELP! Buffer overflow in mio codice!\"\n\"Unix vulnerabilities database (updated)\"\n\nDai una scorsa veloce, ma non c'è niente che non sappia già."),
	Storia.new("1.2.3", "games & demos", "La sezioni giochi è piena di discussioni su nuove release e recensioni:\n\"DOOM - Il miglior FPS di sempre?\"\n\"Shareware: Vale la pena registrare?\"\n\"Demo scene: risultati della competition Bytes United\"\n\"Cerco trucchi per Monkey Island 2\"\n\"Qualcuno ha Ultima VII?\"\n\nInteressante, ma non è quello che ti serve stasera."),
	Storia.new("1.2.4", "download", "accedi all’area download, ma un messaggio ti blocca\n\nACCESSO LIMITATO\nPer scaricare file in questa sezione è necessario essere membri di livello \"Elite\" (100+ post)\n\nIl tuo livello attuale: Regular (47 post)"),
	Storia.new("1.2.5", "system messages", "controlli i messaggi di sistema:\n\n- Il server sarà offline per manutenzione il 28/11 dalle 3:00 alle 7:00\n- Nuovo regolamento sullo scambio di software: leggere prima di postare\n- Congratulazioni a DATANINJA promosso a moderatore dell'area Programming"),
	Storia.new("1.2.6", "Echo Chamber","Stai per disconnetterti quando noti un nuovo forum nella parte inferiore della lista, che non avevi mai visto prima:\n\n[?] Echo Chamber (Accesso solo su invito)\n\nLa descrizione recita semplicemente: \"Solo i prescelti possono accedere. Controlla la tua email.\""),
	Storia.new("1.3", "controlla la posta elettronica", "Apri il tuo client email e attendi mentre scarica i nuovi messaggi. Tra le solite newsletter e spam, un messaggio cattura immediatamente la tua attenzione:\n\nDa: <encrypted>\nOggetto: <encrypted>\nData: 11/11/1993 23:17\n\nIl corpo del messaggio è completamente cifrato:\n\nVabgk1930XJTMB67$qpznvMNS75%trlszPQWI82+ubdgr\nHJK57#yxcbeUIOP09!dswqqLMN46@rtyhgFGH38^poiuy\n\nTi incuriosisce. Non ricevi spesso email cifrate, e questa sembra utilizzare un algoritmo sofisticato. Fortunatamente, la crittografia è stata una delle tue specializzazioni all'MIT.\nDopo circa venti minuti di analisi e tentativi, individui il pattern: una variante dell'algoritmo Vigenère con salti numerici e sostituzione posizionale. Utilizzando le tue conoscenze, riesci a decifrare il messaggio:\n\nIP: 192.168.34.76\nPORTA: 23331\nPASSWORD: prometeus\n\nSe cerchi qualcosa di più delle briciole che ti lasciano a MicroTech, questo è il tuo biglietto d'ingresso.\n\n- DK"),
	Storia.new("1.3.1", "ignora la mail", ""),
	Storia.new("2", "accedi al'ip", "> telnet 192.168.34.76 23331\nTentativo di connessione a 192.168.34.76:23331...\nConnessione stabilita.\n\nLo schermo diventa nero per un istante, poi appare un'interfaccia minimalista, completamente diversa da qualsiasi BBS tu abbia mai visto:\n┌──────────────────────────────────────────────┐\n│                                              │\n│    ███████╗ ██████╗██╗  ██╗ ██████╗          │\n│    ██╔════╝██╔════╝██║  ██║██╔═══██╗         │\n│    █████╗  ██║     ███████║██║   ██║         │\n│    ██╔══╝  ██║     ██╔══██║██║   ██║         │\n│    ███████╗╚██████╗██║  ██║╚██████╔╝         │\n│    ╚══════╝ ╚═════╝╚═╝  ╚═╝ ╚═════╝          │\n│                                              │\n│              CHAMBER v1.3                    │\n│                                              │\n│   \"Le informazioni vogliono essere libere\"   │\n│                                              │\n└──────────────────────────────────────────────┘\nPassword:*********\n\nLa schermata cambia, mostrandoti quella che sembra essere una versione molto più avanzata e raffinata di qualsiasi forum tu abbia mai visto. L'interfaccia è minimalista ma elegante, con un design che sembra venire dal futuro.\n\n┌──────────────────────────────────────────────────────────────────┐\n│ ECHO CHAMBER                        Utenti connessi: 12          │\n├──────────────────────────────────────────────────────────────────┤\n│                                                                  │\n│ BACHECA PRINCIPALE                                               │\n│ ► Manifesto della Libertà Digitale [DARKKNIGHT]                  │\n│ ► Next-Gen Encryption Methods [CIPHER]                           │\n│ ► La nascita dell'economia digitale [NEUROMANCER]                │\n│ ► Digital Underground: opportunità e rischi [TESLA_X]            │\n│ ► CryptoValue: la moneta del futuro? [VALIS]                     │\n│ ► Black Markets: revolution or evolution? [PHANTOM]              │\n│                                                                  │\n│ MESSAGGISTICA PRIVATA                                            │\n│ [!] 1 nuovo messaggio da: DARKKNIGHT                             │\n│                                                                  │\n└──────────────────────────────────────────────────────────────────┘"),
	Storia.new("2.1", "post di DarkKnight", "════════════════════════════════════════════════════════════════════\nMANIFESTO DELLA LIBERTÀ DIGITALE\nAutore: DARKKNIGHT | Pubblicato: 09/11/1993 | Risposte: 17\n════════════════════════════════════════════════════════════════════\n\nSiamo all'alba di una nuova era. Un'era in cui le informazioni scorreranno libere come fiumi, ignorando confini, censure, controlli.\n\nNoi, gli esploratori di questa nuova frontiera digitale, abbiamo una responsabilità: costruire gli strumenti che permetteranno questa rivoluzione silenziosa.\n\nMentre i governi e le corporation cercano di recintare internet, di commercializzarlo e controllarlo, noi lavoriamo nell'ombra per mantenere aperti i canali di comunicazione.\n\nLe reti appartengono a tutti. I dati appartengono a tutti.\nIl codice è poesia, e noi siamo i poeti di questa nuova era.\n\nChi è con me?\n\n--------------------------------------------------------------------\n\nSegue una serie di risposte entusiaste da vari utenti, alcune tecniche, altre più filosofiche. CIPHER ha risposto con una lunga analisi tecnica degli strumenti necessari, mentre PHANTOM ha contribuito con alcuni commenti provocatori sull'autorità stabilita. TESLA_X ha offerto idee pratiche sull'implementazione.\n\nNoti che DARKKNIGHT sembra avere un certo carisma e un seguito considerevole all'interno della comunità."),
	Storia.new("2.2", "post di Phantom", "════════════════════════════════════════════════════════════════════\nBLACK MARKETS: REVOLUTION OR EVOLUTION?\nAutore: PHANTOM | Pubblicato: 10/11/1993 | Risposte: 11\n════════════════════════════════════════════════════════════════════\n\nLa prossima frontiera per l'economia digitale sarà quella che io chiamo \"dark markets\" - mercati completamente anonimi, non tracciabili e fuori dal controllo di qualsiasi giurisdizione.\n\nCon il prototipo di NEUROMANCER, la crittografia avanzata e le reti anonimizzate, sarà possibile creare spazi commerciali dove la domanda e l'offerta si incontrano liberamente, senza interferenze esterne.\n\nImmaginate un Amazon del futuro, dove chiunque può vendere qualsiasi cosa a chiunque, ovunque, in maniera completamente anonima.\n\nOvviamente, questo solleva questioni etiche. Ma il punto è che la tecnologia lo renderà possibile, che lo vogliamo o no. Quindi è meglio discuterne apertamente, qui, tra pionieri.\n\nLa domanda è: questi mercati rappresentano un'evoluzione naturale del commercio o una rivoluzione contro il sistema esistente?\n\nQuesto thread ha generato il dibattito più acceso. Alcuni utenti sono entusiasti delle possibilità, altri esprimono preoccupazioni etiche sui potenziali abusi. TESLA_X sembra essere uno dei più cauti, sottolineando la necessità di auto-regolamentazione, mentre VALIS sostiene che i mercati liberi tendono naturalmente a stabilire norme e standard.\nDARKKNIGHT ha assunto una posizione moderata, riconoscendo sia le opportunità che i rischi.\n\nIl dibattito tocca anche questioni filosofiche profonde sulla libertà individuale, la responsabilità e l'anarchia. Ti ritrovi coinvolto intellettualmente, riflettendo sulla tua posizione."),
	Storia.new("2.3", "post di Cipher", "════════════════════════════════════════════════════════════════════\n  NEXT-GEN ENCRYPTION METHODS\n  Autore: CIPHER | Pubblicato: 10/11/1993 | Risposte: 8\n════════════════════════════════════════════════════════════════════\n\nCome molti di voi sanno, gli attuali metodi di crittografia a 40 bit stanno per diventare obsoleti. Ho sviluppato un algoritmo ibrido che combina RSA con una chiave a 128 bit e un layer aggiuntivo di crittografia one-time pad basata su sequenze pseudo-casuali.\n\nNei miei test, un supercomputer Cray avrebbe bisogno di circa 20 anni per forzare questa crittografia con un attacco brute force.\n\nHo intenzione di rilasciarlo come open source nelle prossime settimane, ma prima vorrei che alcuni di voi lo testassero.\nCerco 3-5 programmatori esperti in crittografia.\n\nLo scopo? Creare canali di comunicazione completamente sicuri, anche dalle agenzie governative più avanzate.\n\nChi è interessato può contattarmi privatamente.\n\n--------------------------------------------------------------------\n\nLe risposte sono principalmente tecniche, con domande sull'implementazione e richieste di partecipare ai test. CIPHER risponde in modo dettagliato e competente, dimostrando una conoscenza approfondita della crittografia. DARKKNIGHT ha lodato l'approccio, suggerendo alcuni miglioramenti all'algoritmo. VALIS ha sollevato alcune preoccupazioni sulla struttura dei pacchetti che potrebbero lasciare tracce identificabili."),
	Storia.new("2.4", "post di Neuromancer", "════════════════════════════════════════════════════════════════════\nLA NASCITA DELL'ECONOMIA DIGITALE\nAutore: NEUROMANCER | Pubblicato: 08/11/1993 | Risposte: 21\n════════════════════════════════════════════════════════════════════\n\nHo sviluppato un prototipo funzionante di quello che chiamo \"Digital Currency System\" o DCS.\n\nÈ un sistema completamente decentralizzato che sfrutta la crittografia a chiave pubblica/privata per consentire transazioni sicure e anonime senza bisogno di intermediari come banche o governi.\n\nOgni transazione viene verificata da un network distribuito di computer e registrata in un \"libro mastro\" pubblico ma crittografato.\n\nHo bisogno di volontari per testare il sistema. Se funziona, potrebbe rivoluzionare l'economia globale e creare un sistema finanziario parallelo completamente fuori dal controllo di qualsiasi autorità.\n\nChi vuole essere parte della rivoluzione?\n\n--------------------------------------------------------------------\n\nLe risposte sono un mix di entusiasmo, scetticismo tecnico e discussioni filosofiche sul futuro dell'economia. NEUROMANCER risponde pazientemente a tutte le domande, dimostrando una comprensione profonda sia della crittografia che dell'economia. TESLA_X ha offerto alcune soluzioni per migliorare la scalabilità del sistema, mentre PHANTOM ha espresso entusiasmo per le implicazioni politiche di una valuta totalmente decentralizzata.\n\nTi colpisce come questo concetto sembri incredibilmente avanti rispetto a qualsiasi cosa tu abbia sentito prima. Un'economia digitale completamente decentralizzata? Suona quasi utopico."),
	Storia.new("2.5", "post di Tesla_x", "════════════════════════════════════════════════════════════════════\nDIGITAL UNDERGROUND: OPPORTUNITÀ E RISCHI\nAutore: TESLA_X | Pubblicato: 07/11/1993 | Risposte: 15\n════════════════════════════════════════════════════════════════════\n\nMentre sviluppiamo queste tecnologie rivoluzionarie, dobbiamo anche considerare le implicazioni di sicurezza personale per tutti noi.\n\nLe agenzie governative stanno iniziando a prestare attenzione a ciò che facciamo. Non sottovalutiamo la loro determinazione o le loro risorse.\n\nPropongo di stabilire un protocollo di sicurezza operativa (OPSEC) per tutti i membri dell'Echo Chamber:\n1. Utilizzare sempre VPN o meglio Tor quando ci si connette\n2. Mantenere identità digitali e reali completamente separate\n3. Evitare di usare lo stesso pseudonimo su piattaforme diverse\n4. Non discutere mai dettagli personali, anche in canali privati\n5. Rotazione regolare delle chiavi di crittografia e password\n\nQueste misure non sono paranoiche, ma necessarie nel mondo in cui stiamo entrando. Ricordate che ciò che stiamo costruendo potrebbe sconvolgere potenti interessi consolidati.\n\nAggiungete i vostri suggerimenti nei commenti.\n\n--------------------------------------------------------------------\n\nLe risposte mostrano vari livelli di preoccupazione. PHANTOM sembra quasi noncurante dei rischi, mentre CIPHER e VALIS hanno aggiunto suggerimenti tecnici dettagliati per migliorare la sicurezza. DARKKNIGHT ha condiviso alcune storie inquietanti di hacker arrestati, sottolineando l'importanza della cautela.\n\nQuesto thread ti fa riflettere sulla serietà di ciò in cui ti stai potenzialmente coinvolgendo. Non è solo un gioco intellettuale, ma qualcosa con potenziali conseguenze nel mondo reale."),
	Storia.new("2.6", "post di Valis", "════════════════════════════════════════════════════════════════════\nCRYPTOVALUE: LA MONETA DEL FUTURO?\nAutore: VALIS | Pubblicato: 11/11/1993 | Risposte: 14\n════════════════════════════════════════════════════════════════════\n\nPartendo dal prototipo di NEUROMANCER, ho calcolato alcune proiezioni economiche per il futuro di questa \"cryptovaluta\".\n\nSe anche solo l'1% dell'economia globale adottasse questo sistema entro il 2000, una singola unità di questa valuta potrebbe valere migliaia di dollari.\n\nMa il vero valore non sta nel potenziale speculativo, ma nella libertà che offre: transazioni anonime, nessun controllo centrale, nessuna inflazione arbitraria decisa da banche centrali.\n\nImmaginate un mondo in cui potete gestire il vostro denaro senza che nessuno vi controlli o vi tacci. Un mondo in cui le transazioni internazionali sono istantanee e praticamente gratuite.\n\nÈ la fine del sistema bancario come lo conosciamo. E l'inizio di qualcosa di meglio.\n\nLe risposte sono appassionate, con discussioni dettagliate sul potenziale impatto economico e sociale di un sistema del genere. VALIS sembra essere un economista o comunque qualcuno con una solida formazione finanziaria. NEUROMANCER ha approfondito alcuni aspetti tecnici, mentre DARKKNIGHT ha sollevato questioni interessanti sulla governance di un simile sistema. C'è una risposta di un nuovo utente, SHADOWWALKER, che solleva domande scettiche sul valore intrinseco di una valuta puramente digitale."),
	Storia.new("3", "messaggio privato da KarkKnight", "════════════════════════════════════════════════════════════════════\nMESSAGGIO PRIVATO\nDa: DARKKNIGHT | Inviato: 11/11/1993 23:47\n════════════════════════════════════════════════════════════════════\n\nBenvenuto, £.\n\nSono contento che tu abbia deciso di fare il grande passo.\n\nTi ho osservato per un po'. I tuoi contributi su alcuni forum tecnici, il codice che hai condiviso, le soluzioni innovative che hai proposto...\nHai un talento raro. Un talento che sta marcendo in quella piccola azienda che non apprezza il tuo valore.\n\nQui, nell'Echo Chamber, siamo un gruppo selezionato di menti che condividono una visione: portare la vera libertà nell'era digitale. Libertà di informazione, di commercio, di identità.\n\nAbbiamo bisogno di persone come te. Persone che vedono oltre i confini convenzionali della tecnologia e della società.\n\nSe sei interessato a saperne di più, partecipa alla chat privata stanotte a mezzanotte. Useremo il canale crittografato #shadownet. La chiave di accesso è: nebula7.\n\nQuesta è un'opportunità unica, Alex. Un'opportunità di cambiare la tua vita e, forse, il mondo intero.\n\n- DK\n\n--------------------------------------------------------------------\n\nIl messaggio ti lascia con un mix di curiosità e cautela. Chi è veramente questo DARKKNIGHT? Come fa a sapere così tanto di te? E soprattutto, cosa sta offrendo esattamente?\n\nUna cosa è certa: stai entrando in qualcosa di molto più grande e complesso di quanto immaginassi. La scelta se proseguire o meno è tua."),
	Storia.new("3.1", "esplora ancora l’Echo Chamber", "┌──────────────────────────────────────────────────────────────────┐\n│ ECHO CHAMBER                        Utenti connessi: 12          │\n├──────────────────────────────────────────────────────────────────┤\n│                                                                  │\n│ PROFILI UTENTE                                                   │\n│ ► DARKKNIGHT (Amministratore)                                    │\n│ ► PHANTOM (Moderatore)                                           │\n│ ► CIPHER (Moderatore)                                            │\n│ ► NEUROMANCER (Membro Elite)                                     │\n│ ► TESLA_X (Membro Elite)                                         │\n│ ► VALIS (Membro Elite)                                           │\n│ ► ... altri utenti ...                                           │\n└──────────────────────────────────────────────────────────────────┘\n\nQuale profilo vuoi visualizzare?"),
	Storia.new("3.1.1", "DarkKnight", "════════════════════════════════════════════════════════════════════\nPROFILO UTENTE: DARKKNIGHT\nRuolo: Amministratore | Membro dal: 12/04/1991\n════════════════════════════════════════════════════════════════════\n\nContributi: 1,247\nProgetti: CryptoNet, ShadowScript, DeepVault\n\n\"La vera libertà esiste solo nel regno digitale, dove i bit non conoscono confini o leggi al di fuori di quelle della matematica.\"\nCompetenze: Crittografia avanzata, Architetture di rete, Kernel development, Sicurezza informatica\n\nNote: Fondatore dell'Echo Chamber e pioniere delle comunicazioni sicure. Ha presentato \"Architetture di rete resistenti alla sorveglianza\" alla DefCon 1992 (sotto pseudonimo)."),
	Storia.new("3.1.2", "Phantom", "════════════════════════════════════════════════════════════════════\nPROFILO UTENTE: PHANTOM\nRuolo: Moderatore | Membro dal: 17/09/1991\n════════════════════════════════════════════════════════════════════\n\nContributi: 973\nProgetti: AnonyMail, ShadowNet, DeepProxy\n\n\"La tecnologia è l'arma dei nuovi rivoluzionari. Il codice è il nostro manifesto.\"\n\nCompetenze: Reverse engineering, Network protocols, System vulnerabilities, Distributed computing\n\nNote: Specializzato in sistemi di comunicazione resistenti alla censura. Approccio pragmatico e creativo ai problemi tecnici. Tendenza a sfidare le soluzioni convenzionali con approcci non ortodossi."),
	Storia.new("3.1.3", "Chiper", "════════════════════════════════════════════════════════════════════\nPROFILO UTENTE: CIPHER\nRuolo: Moderatore | Membro dal: 29/11/1991\n════════════════════════════════════════════════════════════════════\n\nContributi: 842\nProgetti: QuietTalk, PolyCode, SecureVault\n\n\"La crittografia è l'ultima arte di dire la verità in un mondo i menzogne.\"\n\nCompetenze: Crittografia matematica, Algoritmi di cifratura, Protocolli di comunicazione sicura, Teoria dei numeri\n\nNote: Background accademico in matematica pura. Approccio rigoroso e metodico allo sviluppo di sistemi crittografici. Ha pubblicato diversi papers teorici sotto pseudonimi diversi."),
	Storia.new("3.1.4", "Neuromancer", "════════════════════════════════════════════════════════════════════\nPROFILO UTENTE: NEUROMANCER\nRuolo: Membro Elite | Membro dal: 03/06/1992\n════════════════════════════════════════════════════════════════════\n\nContributi: 1,105\nProgetti: Digital Currency System (DCS), AnonLedger, CryptoMesh\n\n\"La vera rivoluzione non è tecnica, ma economica. Cambia il modo in cui le persone scambiano valore, e cambierai il mondo.\"Competenze: Sistemi di pagamento decentralizzati, Blockchain, Crittografia applicata, Economia digitale, Protocolli P2P\n\nNote: Visionario dell’economia digitale, NEUROMANCER ha ideato il primo prototipo di valuta decentralizzata dell’Echo Chamber. Background in matematica applicata e informatica. Ha pubblicato white paper sotto vari pseudonimi. Si dice abbia lavorato per un istituto di ricerca governativo, ma non ha mai confermato né smentito."),
	Storia.new("3.1.5", "Tesla_x", "════════════════════════════════════════════════════════════════════\nPROFILO UTENTE: TESLA_X Ruolo: Membro Elite | Membro dal: 14/02/1992\n════════════════════════════════════════════════════════════════════\n\nContributi: 753\nProgetti: EtherBridge, QuantumLoop, AutonomousNodes\n\n\"L'energia dell'informazione è l'unica risorsa veramente inesauribile.  Dobbiamo solo imparare a incanalare il flusso.\"\n\nCompetenze: Reti distribuite, Architetture P2P, Sistemi di energia  alternativa, Elettronica avanzata\n\nNote: Ingegnere hardware con focus su sistemi di comunicazione a basso  consumo e indipendenti dalla rete elettrica. Promotore dell'integrazione tra tecnologie sostenibili e infrastrutture di comunicazione autonome. Lavora a un progetto sperimentale per nodi di rete alimentati da fonti rinnovabili"),
	Storia.new("3.1.6", "Valis", "════════════════════════════════════════════════════════════════════\nPROFILO UTENTE: VALIS\nRuolo: Membro Elite | Membro dal: 03/05/1992\n════════════════════════════════════════════════════════════════════\n\nContributi: 687\nProgetti: EconoSim, CryptoValue, MarketMatrix\n\n\"I numeri non mentono. Le persone sì. Segui i dati e troverai la verità nascosta dietro ogni sistema, economico o sociale che sia.\"\n\nCompetenze: Economia computazionale, Modelli predittivi, Analisi di mercato, Teoria dei giochi, Sistemi finanziari alternativi\n\nNote: Background accademico in economia e matematica applicata. Approccio analitico e basato sui dati. Specializzato nella creazione di modelli che prevedono il comportamento dei mercati decentralizzati. Ha pubblicato diversi paper sotto pseudonimi su riviste economiche mainstream, influenzando il pensiero accademico senza rivelare la sua vera identità."),
	Storia.new("3.2", "accedi alla chat", "[color=00ffaa]> Connessione a #shadownet in corso...\nAutenticazione richiesta: **********\nAutenticazione completata.\nCrittografia end-to-end attivata.\nBenvenuto in #shadownet, £[/color]\n\n[color=#FFD700]<DARKKNIGHT>[/color]: Benvenuto, £. Puntuale, mi piace.\n[color=#FFD700]<PHANTOM>[/color]: Finalmente conosciamo la new entry. Benvenuto.\n[color=#FFD700]<CIPHER>[/color]: Un piacere averti qui.\n[color=#FFD700]<TESLA_X>[/color]: Un altro ingegnere nel gruppo? Ottimo.\n[color=#FFD700]<VALIS>[/color]: Eccomi, scusate il ritardo.\n[color=#FFD700]<DARKKNIGHT>[/color]: Ora che ci siamo tutti, possiamo iniziare. £, ti starai chiedendo perché sei qui.\n[color=#39FF14]<£>[/color]: In effetti sì. E come fate a sapere così tanto di me?\n[color=#FFD700]<PHANTOM>[/color]: Internet è un posto piccolo per chi sa come navigarlo davvero.\nE noi siamo molto, molto bravi a navigarlo.\n[color=#FFD700]<DARKKNIGHT>[/color]: Siamo un gruppo di... diciamo visionari. Persone che credono che la tecnologia dovrebbe liberare l'umanità, non imprigionarla.\n[color=#FFD700]<CIPHER>[/color]: Stiamo costruendo gli strumenti del futuro. Un futuro in cui le persone potranno comunicare, scambiare beni e informazioni, esistere digitalmente senza controlli o limitazioni.\n[color=#FFD700]<VALIS>[/color]: Il sistema attuale è corrotto. Banche, governi, corporation - tutti vogliono una fetta della tua libertà, della tua privacy, dei tuoi dati.\n[color=#FFD700]<DARKKNIGHT>[/color]: Noi stiamo creando le alternative. Reti anonime, valute digitali, mercati non regolamentati. E per farlo, abbiamo bisogno dei migliori.\n[color=#39FF14]<£>[/color]: E perché proprio io?\n[color=#FFD700]<DARKKNIGHT>[/color]: La tua soluzione per l'algoritmo di routing distribuito che hai postato l'anno scorso su alt.programming era geniale. Ha risolto un problema che stavamo affrontando da mesi.\n[color=#FFD700]<PHANTOM>[/color]: E il tuo lavoro sulla crittografia a chiave multipla è... interessante.\n[color=#FFD700]<DARKKNIGHT>[/color]: Ti offriamo un posto nel nostro circolo interno. Un lavoro vero, retribuito in cryptovaluta. Più soldi di quanti ne farai mai alla MicroTech. E, soprattutto, la libertà di creare senza limiti.\n[color=#FFD700]<NEUROMANCER>[/color]: C'è un progetto specifico per cui vorremmo il tuo aiuto. Qualcosa che cambierà il modo in cui le persone interagiscono con l'economia digitale.\n[color=#FFD700]<DARKKNIGHT>[/color]: Ti interessa?"),
	Storia.new("3.2.1", "Quanto è legale tutto questo?", "DARKKNIGHT: *ride* La legalità è una costruzione artificiale, £. Una linea arbitraria disegnata da persone che vogliono mantenere il controllo.\nCIPHER: Le leggi attuali non sono state scritte per il mondo digitale. Sono obsolete, create da persone che non capiscono nemmeno cosa sia un protocollo TCP/IP.\nPHANTOM: Diciamo che operiamo in una zona grigia. In un territorio inesplorato dove le regole non sono ancora state scritte.\nTESLA_X: Pensa ai pionieri del West americano. Non stavano infrangendo le leggi - stavano esplorando territori dove le leggi non esistevano ancora.\nVALIS: Non siamo criminali, £. Siamo innovatori. Visionari. La storia ci darà ragione.\nDARKKNIGHT: Quello che stiamo costruendo aiuterà milioni di persone a sfuggire al controllo di governi oppressivi, di corporation predatorie. Pensa ai dissidenti in regimi totalitari, ai giornalisti che rischiano la vita per la verità.\nNEUROMANCER: La domanda non è se sia legale. La domanda è se sia giusto.\nDARKKNIGHT: Allora, £... sei ancora interessato?\n"),
	Storia.new("3.2.2", "Che tipo di compenso state offrendo esattamente?", "DARKKNIGHT: Diretti, mi piace. Parliamo di compensi nell'ordine di 50 bitcoin al mese.\n£: Bitcoin? Quella roba sperimentale? Vale qualcosa?\nPHANTOM: *sorride* Oggi, non molto. Ma abbiamo fatto i nostri calcoli. Entro dieci anni, quei 50 bitcoin potrebbero valere più di quanto guadagni in cinque anni alla MicroTech.\nCIPHER: Stiamo parlando di creare la valuta del futuro, £. Un sistema monetario completamente decentralizzato, fuori dal controllo di banche e governi.\nTESLA_X: Oltre al compenso in bitcoin, offriamo accesso a tecnologie e conoscenze che non troverai da nessun'altra parte.\nVALIS: Considera che molti di noi hanno background in istituzioni accademiche di alto livello o aziende Fortune 500. Abbiamo scelto di essere qui, nell'ombra, perché crediamo in qualcosa di più grande.\nDARKKNIGHT: E c'è un bonus di benvenuto. 100 bitcoin subito, come segno della nostra buona fede.\nNEUROMANCER: Inoltre, ti daremo gli strumenti per proteggere completamente la tua identità online. Un valore inestimabile in un mondo sempre più sorvegliato.\nDARKKNIGHT: Quindi, £... affare fatto?"),
	Storia.new("3.2.3", "sono interessato. raccontami di più su questo progetto", "£: Sono interessato. Raccontatemi di più su questo progetto.\nDARKKNIGHT: Ottimo. Lo chiamiamo \"The Shadow Bazaar\". Un marketplace completamente decentralizzato e anonimo.\nPHANTOM: Immagina un mercato dove chiunque può vendere qualsiasi cosa a chiunque, ovunque, senza intermediari. Nessuna commissione esagerata, nessuna censura, nessun controllo esterno.\nCIPHER: Utilizzando la cryptovaluta che NEUROMANCER ha sviluppato, tutte le transazioni saranno anonime e non tracciabili.\nVALIS: E con un sistema di reputazione basato su blockchain, gli utenti potranno fidarsi l'uno dell'altro senza mai conoscere le rispettive identità reali.\nDARKKNIGHT: Il tuo ruolo sarebbe sviluppare l'architettura di rete. Abbiamo bisogno di un sistema che possa operare su una rete overlay crittografata, con routing anonimo e resilienza contro gli attacchi.\nPHANTOM: In pratica, devi rendere la piattaforma invisibile alle autorità e resistente a qualsiasi tentativo di spegnerla.\nTESLA_X: I nodi della rete saranno distribuiti globalmente. Se anche il 90% venisse compromesso, il sistema continuerebbe a funzionare.\n£: Suona... ambizioso. E potenzialmente problematico dal punto di vista legale.\nDARKKNIGHT: La tecnologia in sé non è illegale. È solo uno strumento. Come viene usato dipende dagli utenti.\nCIPHER: E poi, le leggi attuali sono decenni indietro rispetto alla tecnologia. Stiamo operando in un'area grigia, una terra di nessuno legislativa.\nPHANTOM: Non stiamo facendo nulla di diverso da quello che fanno le grandi corporation o i governi. Solo che noi lo facciamo per le persone, non contro di loro.\nVALIS: Pensa alla libertà che questo porterà. La possibilità di commerciare liberamente, senza censura o sorveglianza.\nDARKKNIGHT: Quindi, che ne dici? Sei dei nostri?"),
	Storia.new("3.2.3.1", "Prima di decidere, voglio sapere chi siete realmente", "£: Prima di decidere, voglio sapere chi siete realmente.\n\n- Silenzio per alcuni secondi\n\nDARKKNIGHT: Una richiesta ragionevole, ma pericolosa.\nPHANTOM: La paranoia è una virtù in questo ambiente, £.\nCIPHER: Le identità reali sono la valuta più preziosa nel nostro mondo.\nDARKKNIGHT: Posso dirti che alcuni di noi hanno lavorato per agenzie governative. Altri per corporation tech. Qualcuno è ancora dentro, agendo come... consulente esterno.\nTESLA_X: Io ero alla DARPA, programma di ricerca avanzata sulle comunicazioni quantistiche. Ho visto cosa stanno costruendo. È per questo che sono qui ora.\nVALIS: Io sono stato in una delle Big Five. Il mio codice gira su milioni di dispositivi. Ho contribuito a creare il sistema di sorveglianza che ora combattiamo.\nNEUROMANCER: Istituto di ricerca governativo. Dipartimento che ufficialmente non esiste.\nCIPHER: Facoltà di matematica applicata. Stanford. Poi NSA. Poi... beh, ho fatto una scelta.\nPHANTOM: Ex consulente di sicurezza informatica per banche centrali. Ho visto come manipolano i mercati, come tracciano ogni transazione.\nDARKKNIGHT: Quanto a me... diciamo solo che ho contribuito a creare alcuni dei protocolli di sicurezza che ora utilizziamo per combattere il sistema.\nDARKKNIGHT: È abbastanza, £? O hai bisogno di nomi e indirizzi? *tono ironico*\n£: No, capisco. Solo... volevo essere sicuro di con chi sto lavorando.\nDARKKNIGHT: Non lavorare con noi, £. Lavora con le nostre idee. Con la visione. Le persone dietro di essa sono irrilevanti.\nDARKKNIGHT: Allora, cosa hai deciso?"),
	Storia.new("3.2.3.2", "Ho bisogno di pensarci. È una decisione importante.", "£: Ho bisogno di pensarci. È una decisione importante.\nDARKKNIGHT: *pausa* Capisco la tua cautela, £. È saggio.\nCIPHER: Non tutti sono pronti per fare questo salto. Richiede coraggio.\nPHANTOM: O forse solo disperazione. *ride sommessamente*\nVALIS: Prenditi il tempo che ti serve. Ma non troppo. Le opportunità come questa non durano per sempre.\nTESLA_X: Posso dirti che all'inizio avevo le tue stesse esitazioni. Ora non tornerei indietro per nulla al mondo.\nDARKKNIGHT: Ti daremo accesso a una parte limitata del nostro repository. Esaminalo, valuta il codice, vedi da solo di cosa si tratta realmente.\nNEUROMANCER: E prendi questi 10 bitcoin come... diciamo, un incentivo a considerare seriamente la nostra offerta.\nDARKKNIGHT: Ti ricontatteremo tra tre giorni, stesso canale, stessa ora. Se non ti presenti, capiremo la risposta.\nPHANTOM: E naturalmente, questa conversazione non è mai avvenuta.\nDARKKNIGHT: A presto, £. O mai più.\n> Connessione terminata.\n\nI giorni passano, il saldo del tuo conto ora è in negativo e capisci che non c’è altra possibilità che ricontattarli."),
	Storia.new("3.2.3.3", "sono dentro, da dove cominciamo?", "£: Sono dentro. Da dove cominciamo?\nDARKKNIGHT: Eccellente scelta, £. Non te ne pentirai.\nPHANTOM: Benvenuto nel team. È bello avere finalmente qualcuno che capisce veramente il routing distribuito.\nNEUROMANCER: Ti invierò tutta la documentazione tecnica esistente. Possiamo programmare una sessione di lavoro dettagliata domani.\nDARKKNIGHT: Per ora, ecco le credenziali di accesso al nostro repository privato. Contiene tutto il codice attuale del progetto e la documentazione.\nCIPHER: Ho creato un wallet per te. Dentro troverai un acconto di 5 CryptoValue. Tra qualche mese varranno più di $3,000. Considera questo solo un anticipo.\nTESLA_X: Se vuoi, posso aiutarti a configurare un ambiente di sviluppo sicuro. Ho scritto un tool che crea una VM completamente isolata con routing attraverso nodi anonimi.\nDARKKNIGHT: Benvenuto nell'Echo Chamber. Insieme, cambieremo le regole del gioco.")
]


var temp = {
	"0": false,
	"0.1": false,
	"0.2": false,
	"0.3": false,
	"1": false,
	"1.1": false,
	"1.1.1": false,
	"1.1.2": false,
	"1.2": false,
	"1.2.1": false,
	"1.2.2": false,
	"1.2.3": false,
	"1.2.4": false,
	"1.2.5": false,
	"1.2.6": false,
	"1.3": false,
	"1.3.1": false,
	"2": false,
	"2.1": false,
	"2.2": false,
	"2.3": false,
	"2.4": false,
	"2.5": false,
	"2.6": false,
	"3": false,
	"3.1": false,
	"3.1.1": false,
	"3.1.2": false,
	"3.1.3": false,
	"3.1.4": false,
	"3.1.5": false,
	"3.1.6": false,
	"3.2": false,
	"3.2.1": false,
	"3.2.2": false,
	"3.2.3": false,
	"3.2.3.1": false,
	"3.2.3.2": false,
	"3.2.3.3": false
}

func load_visited() -> void:
	if FileAccess.file_exists(path_visited):
		var file = FileAccess.open(path_visited, FileAccess.READ)
		var contenuto = file.get_as_text()
		file.close()

		var risultato = JSON.parse_string(contenuto)
		if risultato is Dictionary:
			temp = risultato
			for i in temp:
				if temp[i] == true:
					get_scene_class(i).set_visited()

func write_visited() -> void:
		for i in storia_classed:
			temp[i.get_scene_id()] = i.get_visited()
		scrivi_su_file(temp, path_visited)

func write_data():
	scrivi_su_file(save_data, path)


func scrivi_su_file(dati: Dictionary, path_in: String):
	var file = FileAccess.open(path_in, FileAccess.WRITE)
	file.store_string(JSON.stringify(dati, "\t"))  # "\t" per formattazione leggibile
	file.close()

func get_scene_class(scene_id: String) -> Storia:
	for i in range(len(storia_classed)):
		if storia_classed.get(i).get_scene_id() == scene_id:
			return storia_classed.get(i)
	return null
